export const AGREGAR_PRODUCTO = 'AGREGAR_PRODUCTO';
export const AGREGAR_PRODUCTO_EXITO = 'AGREGAR_PRODUCTO_EXITO';
export const AGREGAR_PRODUCTO_ERROR = 'AGREGAR_PRODUCTO_ERROR';

export const COMENZAR_DESCARGA_PRODUCTOS = 'COMENZAR_DESCARGA_PRODUCTOS';
export const COMENZAR_DESCARGA_EXITO = 'COMENZAR_DESCARGA_EXITO';
export const COMENZAR_DESCARGA_ERROR = 'COMENZAR_DESCARGA_ERROR';